version: '2'

services:
  flask-app:
    image: 'butlercam/flask-app'
    ports:
      - '5000:5000'
    environment:
      - REDIS_SERVER=redis
    volumes:
    # Path on the host, relative to the Compose file
    - ../images/flask-app/flask:/appenv

  redis:
    image: 'butlercam/redis-server'
    ports:
      - '6379'
