version: '2'

services:
  flask-app:
    ports:
      - '5000:5000'
    volumes:
    # Path on the host, relative to the Compose file
      - '/c/Users/Tristan/Desktop/intro-to-docker/images/flask-app/flask':'/appenv'
