version: '2'

services:
  flask-app:
    image: 'butlercam/flask-app'
    ports:
      - '5000'
    environment:
      - REDIS_SERVER=redis

  redis:
    image: 'butlercam/redis-server'
    ports:
      - '6379'
